# cleaned, lowercase, safe keyword list (broad version)

KEYWORDS = [

    # blue economy & ocean governance
    "ocean",
    "marine",
    "coast",
    "coastal",
    "blue economy",
    "sustainable blue economy",
    "ocean economy",
    "marine economy",
    "sustainable ocean economy",
    "ocean governance",
    "marine governance",
    "ocean strategy",
    "blue economy strategy",
    "sustainable ocean plan",
    "marine spatial plan",
    "marine spatial planning",
    "marine plan",
    "msp",
    "national ocean plan",
    "marine policy",
    "ocean policy",

    # marine conservation, biodiversity & fisheries
    "marine protected area",
    "mpa",
    "protected area",
    "other effective area-based conservation measure",
    "oecm",
    "marine conservation zones",
    "mczs",
    "special areas of conservation",
    "sacs",
    "highly protected marine area",
    "hpma",
    "biodiversity beyond national jurisdiction",
    "bbnj",
    "abnj",
    "coastal management",
    "coastal zone management",
    "marine management",
    "integrated marine management",
    "integrated coastal zone management",
    "iczm",
    "marine conservation",
    "ocean biodiversity",
    "marine biodiversity",
    "biodiversity management",
    "fisheries management",
    "sustainable fisheries",
    "aquaculture",
    "sustainable aquaculture",
    "fisheries value chain",
    "mariculture",
    "seafood production",
    "fish stock assessment",
    "fish farming",
    "fisheries technology",
    "fisher",
    "fisherfolk",
    "small-scale fisheries",
    "artisanal fisheries",
    "ecosystem-based management",
    "ecosystem approach to fisheries management",
    "ebm",
    "eafm",
    "stock monitoring",
    "catch documentation",
    "vessel monitoring systems",
    "vms",
    "illegal unreported unregulated fishing",
    "iuu",
    "fisheries compliance",
    "licensing systems",
    "quota management",
    "fish processing",
    "traceability systems",
    "post-harvest handling",

    # mel / m&e / programme evaluation
    "monitoring evaluation and learning",
    "mel",
    "monitoring and evaluation",
    "evaluation",
    "mrv",
    "programme evaluation",
    "impact evaluation",
    "impact monitoring",
    "theory of change",
    "evidence framework",
    "learning system",
    "lessons learned",

    # marine monitoring & data
    "marine monitoring",
    "monitoring programme",
    "marine data",
    "marine evidence",
    "ecosystem monitoring",
    "ecosystem services assessment",
    "pressures mapping",
    "marine autonomous systems",
    "remote electronic monitoring",
    "satellite surveillance",
    "remote sensing",
    "edna",
    "low-carbon monitoring technologies",

    # ocean / climate adaptation & resilience
    "ocean climate",
    "climate change",
    "climate adaptation",
    "coastal adaptation",
    "coastal resilience",
    "climate resilience planning",
    "climate vulnerability",
    "climate risk",
    "ocean risk",
    "nature-based solutions",
    "nbs",
    "ecosystem-based solutions",
    "blue carbon",
    "national adaptation plan",
    "nap",
    "nationally determined contribution",
    "ndc",
    "climate finance indicators",
    "resilience indicators",
    "transformative change indicators",

    # sustainable finance, investment & advisory
    "sustainable finance",
    "ocean finance",
    "blue finance",
    "marine finance",
    "nature finance",
    "ocean investment",
    "ocean impact investment",
    "nature-positive investment",
    "investment framework",
    "assurance framework",
    "financial disclosure",
    "blended finance",
    "natural capital",
    "ecosystem service valuation",
    "ocean accounting",
    "nature market",
    "blue bond",
    "green climate fund",
    "gcf",
    "global environment facility",
    "gef",

    # offshore energy, renewables & decommissioning
    "offshore wind",
    "offshore renewables",
    "offshore renewable energy",
    "marine renewables",
    "offshore energy transition",
    "decommissioning",
    "oil and gas decommissioning",
    "carbon capture and storage",
    "ccs",
    "marine carbon dioxide removal",
    "mcdr",
    "cumulative impacts",
    "nature positive",
    "environmental co-benefits",

    # marine licensing & regulatory reform
    "marine licensing",
    "marine regulation",
    "marine consenting",
    "strategic environmental assessment",
    "eia",
    "habitats regulation assessment",

    # services
    "technical assistance",
    "capacity building",
    "capacity needs assessment",
    "systems mapping",
    "policy mapping",
    "stakeholder mapping",
    "stakeholder analysis",
    "sector plan",
    "sectoral plan",
    "situational analysis",
    "institutional analysis",
    "organisational design",
    "policy framework",
    "regulatory framework",
    "feasibility study",
    "literature review",
    "evidence review",
    "baseline study",
    "needs assessment",
    "stakeholder consultation",
    "training",
    "workshop design and delivery",

    # research, impact & science
    "research impact",
    "impact management",
    "impact pathway design",
    "science advice",
    "evidence synthesis",
    "research programme governance",
    "programme mobilisation",
    "research commissioning",
    "call design",
    "evidence gap analysis",
    "research prioritisation",
    "prioritisation framework",
    "consortium development",
    "programme scoping",
    "marine research",
    "programme design",
    "programme management",
    "policy impact",
    "science communication",
    "policy briefs",
    "knowledge transfer",
    "horizon scanning",
    "strategic foresight",
    "scenario analysis",
    "cumulative impact assessment"
]
