KEYWORDS = [

    # Blue Economy Planning & Transition
    "ocean",
    "marine",
    "coast",
    "coastal",
    "blue economy",
    "sustainable blue economy",
    "ocean economy",
    "marine economy",
    "sustainable ocean economy",
    "ocean governance",
    "marine governance",
    "ocean strategy",
    "blue economy strategy",
    "sustainable ocean plan",
    "sop",
    "marine spatial plan",
    "marine spatial planning",
    "msp",
    "marine plan",
    "marine planning",
    "national ocean plan",
    "marine policy",
    "ocean policy",

    # Marine Conservation, Spatial Management & Biodiversity
    "marine protected area",
    "mpa",
    "other effective area-based conservation measures",
    "oecm",
    "marine conservation zones",
    "mczs",
    "special areas of conservation",
    "sacs",
    "highly protected marine area",
    "hpma",
    "biodiversity beyond national jurisdiction",
    "bbnj",
    "areas beyond national jurisdiction",
    "abnj",
    "coastal management",
    "coastal zone management",
    "integrated coastal zone management",
    "iczm",
    "coastal and marine management",
    "integrated marine management",
    "marine management",
    "marine conservation",
    "ocean biodiversity",
    "marine biodiversity",
    "fisheries management",
    "sustainable fisheries",
    "aquaculture",
    "sustainable aquaculture",
    "mariculture",
    "fisheries value chain",
    "fisheries value-chain",
    "fish stock assessment",
    "fisherfolk",
    "small-scale fisheries",
    "small scale fisheries",
    "artisanal fisheries",
    "ecosystem-based management",
    "ecosystem based management",
    "ebm",
    "ecosystem approach to fisheries management",
    "eafm",
    "stock monitoring",
    "catch documentation",
    "vessel monitoring systems",
    "vms",
    "illegal unreported and unregulated fishing",
    "iuu fishing",
    "fisheries compliance",
    "licensing systems",
    "quota management",
    "traceability systems",
    "post-harvest handling",
    "post harvest handling",

    # Monitoring, Evaluation & Learning (MEL)
    "monitoring evaluation and learning",
    "monitoring evaluation & learning",
    "monitoring and evaluation",
    "monitoring & evaluation",
    "mel",
    "m&e",
    "mrv",
    "programme evaluation",
    "impact evaluation",
    "impact monitoring",
    "theory of change",
    "evidence framework",
    "learning system",
    "lessons learned",

    # Marine Monitoring, Data & Evidence
    "marine monitoring",
    "monitoring programme",
    "marine data",
    "monitoring governance",
    "marine evidence",
    "ecosystem monitoring",
    "ecosystem approach",
    "marine biodiversity monitoring",
    "seabed habitat",
    "ecosystem services assessment",
    "pressures mapping",
    "marine autonomous systems",
    "remote electronic monitoring",
    "rem",
    "satellite surveillance",
    "remote sensing",
    "edna",
    "low-carbon monitoring technologies",

    # Ocean / Climate Adaptation & Resilience
    "ocean climate",
    "climate change",
    "climate adaptation",
    "coastal adaptation",
    "coastal resilience",
    "climate resilience planning",
    "climate vulnerability",
    "climate risk",
    "ocean risk",
    "nature-based solutions",
    "nature based solutions",
    "nbs",
    "ocean-based solutions",
    "ocean based solutions",
    "ecosystem-based solutions",
    "ecosystem based solutions",
    "blue carbon",
    "national adaptation plan",
    "nap",
    "nationally determined contribution",
    "ndc",
    "international climate finance indicators",
    "icf indicators",
    "climate change resilience indicators",
    "transformative change indicators",

    # Sustainable Finance, Investment & Advisory
    "sustainable finance",
    "ocean finance",
    "blue finance",
    "marine finance",
    "nature finance",
    "ocean investment",
    "ocean impact investment",
    "nature-positive investment",
    "investment framework",
    "assurance framework",
    "financial disclosure",
    "blended finance",
    "natural capital",
    "ecosystem service valuation",
    "ocean account",
    "nature market",
    "blue bond",
    "green climate fund",
    "gcf",
    "global environment facility",
    "gef",

    # Offshore Energy, Renewables & Decommissioning
    "offshore wind",
    "offshore renewables",
    "offshore renewable energy",
    "ore",
    "marine renewables",
    "offshore energy transition",
    "decommissioning",
    "oil and gas decommissioning",
    "carbon capture and storage",
    "ccs",
    "marine carbon dioxide removal",
    "mcdr",
    "strategic compensation",
    "cumulative impacts",
    "environmental co-benefits",
    "coexistence",
    "co-existence",
    "marine recovery fund",
    "marine net gain",
    "nature-positive",
    "nature positive",
    "net benefit",

    # Marine Licensing & Regulatory Reform
    "marine licensing",
    "marine regulation",
    "marine consenting",
    "strategic environmental assessment",
    "sea",
    "environmental impact assessment",
    "eia",
    "habitats regulations assessment",
    "hra",

    # Services (only low-noise terms)
    "technical assistance",
    "capacity building",
    "capacity needs assessment",
    "advisory",
    "systems mapping",
    "policy mapping",
    "stakeholder mapping",
    "stakeholder analysis",
    "sectoral plan",
    "situational analysis",
    "institutional analysis",
    "organisational design",
    "policy framework",
    "regulatory framework",
    "feasibility study",
    "evidence review",
    "literature review",
    "baseline study",
    "needs assessment",
    "stakeholder consultation",

    # Research, Evidence & Foresight
    "research impact",
    "impact management",
    "impact pathway design",
    "science advice",
    "evidence synthesis",
    "impact tracking",
    "research programme governance",
    "research commissioning",
    "call design",
    "evidence gap analysis",
    "research prioritisation",
    "prioritisation framework",
    "consortium development",
    "programme scoping",
    "marine research",
    "programme design",
    "programme governance",
    "programme management",
    "stakeholder engagement",
    "policy impact",
    "consenting and licensing evidence",
    "investment assurance",
    "economic valuation of research",
    "return on investment",
    "policy briefs",
    "knowledge communication",
    "knowledge exchange",
    "horizon scanning",
    "policy monitoring",
    "scenario analysis",
    "strategic foresight",
    "ecosystem modelling",
    "cumulative impact assessment"
]
