# Tiered keyword lists for marine/ocean tender detection

TIER1_KEYWORDS = [
    # core ocean / marine / coastal
    "ocean",
    "marine",
    "coast",
    "coastal",
    "blue economy",
    "sustainable blue economy",
    "ocean economy",
    "marine economy",
    "sustainable ocean economy",
    "ocean governance",
    "marine governance",
    "ocean strategy",
    "blue economy strategy",
    "marine policy",
    "ocean policy",
    "national ocean plan",

    # marine spatial planning
    "marine spatial plan",
    "marine spatial planning",
    "marine plan",
    "msp",

    # conservation, biodiversity (marine only)
    "marine protected area",
    "mpa",
    "other effective area-based conservation measure",
    "oecm",
    "marine conservation zones",
    "mczs",
    "special areas of conservation",
    "sacs",
    "highly protected marine area",
    "hpma",
    "biodiversity beyond national jurisdiction",
    "bbnj",
    "abnj",
    "marine conservation",
    "marine biodiversity",
    "ocean biodiversity",

    # fisheries & aquaculture
    "fisheries",
    "fisheries management",
    "sustainable fisheries",
    "aquaculture",
    "sustainable aquaculture",
    "mariculture",
    "fish stock assessment",
    "fisherfolk",
    "small-scale fisheries",
    "artisanal fisheries",
    "ecosystem-based management",
    "ebm",
    "eafm",
    "iuu",
    "illegal unreported unregulated fishing",
    "vms",
    "vessel monitoring systems",

    # marine data & monitoring
    "marine monitoring",
    "marine data",
    "marine evidence",
    "marine autonomous systems",
    "marine ecosystem monitoring",
    "pressures mapping",
    "remote electronic monitoring",

    # ocean-climate (marine-specific)
    "coastal adaptation",
    "coastal resilience",
    "ocean climate",
    "ocean risk",
    "blue carbon",

    # blue / ocean finance
    "blue finance",
    "ocean finance",
    "marine finance",

    # offshore energy & decommissioning
    "offshore wind",
    "offshore renewables",
    "offshore renewable energy",
    "marine renewables",
    "offshore energy transition",
    "decommissioning",
    "oil and gas decommissioning",
    "ccs",
    "carbon capture and storage",
    "marine carbon dioxide removal",
    "mcdr",
]

TIER2_KEYWORDS = [
    # broader biodiversity / climate
    "biodiversity",
    "conservation",
    "climate change",
    "climate adaptation",
    "climate resilience",
    "climate vulnerability",
    "climate risk",
    "nature-based solutions",
    "nbs",
    "national adaptation plan",
    "nap",
    "nationally determined contribution",
    "ndc",

    # broader fisheries & supply chain
    "fisheries technology",
    "traceability systems",
    "post-harvest handling",
    "fish farming",
    "seafood production",

    # sustainable finance (general)
    "sustainable finance",
    "nature finance",
    "investment framework",
    "assurance framework",
    "blended finance",
    "natural capital",
    "ecosystem service valuation",
    "ocean accounting",
    "nature market",
    "blue bond",
    "green climate fund",
    "gcf",
    "global environment facility",
    "gef",

    # regulation & environment
    "strategic environmental assessment",
    "eia",
    "habitats regulation assessment",

    # services (very broad — only valid when tier 1 matches)
    "technical assistance",
    "capacity building",
    "capacity needs assessment",
    "systems mapping",
    "policy mapping",
    "stakeholder mapping",
    "stakeholder analysis",
    "situational analysis",
    "institutional analysis",
    "organisational design",
    "policy framework",
    "regulatory framework",
    "feasibility study",
    "literature review",
    "evidence review",
    "baseline study",
    "needs assessment",
    "stakeholder consultation",
    "training",
    "workshop",
    "training course",
    "training delivery",

    # research & impact
    "monitoring and evaluation",
    "mel",
    "evaluation",
    "mrv",
    "programme evaluation",
    "impact evaluation",
    "impact monitoring",
    "theory of change",
    "learning system",
    "lessons learned",
    "research impact",
    "impact management",
    "impact pathway design",
    "science advice",
    "evidence synthesis",
    "programme mobilisation",
    "research commissioning",
    "call design",
    "evidence gap analysis",
    "research prioritisation",
    "consortium development",
    "programme scoping",
    "programme design",
    "policy impact",
    "science communication",
    "policy briefs",
    "knowledge transfer",
    "horizon scanning",
    "strategic foresight",
    "scenario analysis",
]
